#!/usr/bin/env bash
ARGS=""
while [ $# -gt 0 ]; do
	arg=$1
	case $arg in
	-)
		ARGS="$ARGS -L -"	
		;;
	--no-members)
		;;
	*)
		ARGS="ARGS $1"
		;;
	esac
	shift
done
echo "Running with $ARGS"
ctags $ARGS
